Dim default sink instead of each playing client.

diff --git a/vdim b/vdim
--- a/vdim
+++ b/vdim
@@ -3,137 +3,67 @@
 # -6dB dimmer
 # dim/restore volume of playing clients.
 
-declare -a inputs
-declare vol
-declare app
 declare volfile="$HOME/.config/speaker.volume"
 
 __help() {
 cat << 'EOB' >&2
-Vdim: -6dB dimmer for pulseaudio
+Vdim: -6dB dimmer for pulseaudio default sink.
 
 Usage:
-  vdim
-  vdim l | list
-  vdim d | dim
-  vdim r | restore
-  vdim h | help
-
-Options:
-  Invoked without argument, vdim reduces the volume of currently
-  playing applications, or restore their initial volume.
-
-  l, list    - display currently dimmed clients and exit.
-  d, dim     - change volume for undimmed clients only.
-  r, restore - restore dimmed clients only.
-  h, help    - display this help and exit.
+  vdim          - dim/undim default sink.
+  vdim h | help - show this help and exit.
 
 EOB
 }
 
-get_inputs() {
-  local info __r __s
-  __s="[[:space:]]"
-  __r="^([0-9]+)$__s*[0-9]+$__s*([0-9-]+)$__s*.*$"
+dim() {
+  local info index go r1 r2 r3 vol
+  r1="^\* index:[[:space:]]*(.+)$"
+  r2="^used by:[[:space:]]*(.+)$"
+  r3="^volume:[[:space:]]*front\-left:[[:space:]]*([0-9]+).*$"
   while read -r info; do
-    [[ $info =~ $__r ]] && {
-      [[ ${BASH_REMATCH[2]} == "-" ]] && continue
-      inputs+=("${BASH_REMATCH[1]}")
-    }
-  done < <(pactl list sink-inputs short)
-}
-
-get_input_volume() {
-  local info index go
-  index="$1"
-  while read -r info; do
-    [[ $info =~ ^index:[[:space:]]*(.+)$ ]] && {
-      if [[ ${BASH_REMATCH[1]} == "$index" ]]; then go=1; else unset go; fi
+    [[ $info =~ $r1 ]] && {
+      # default sink index
+      index="${BASH_REMATCH[1]}"
+      go=1
+      continue
     }
     [[ $go ]] && {
-        [[ $info =~ ^volume:[[:space:]]*front\-left:[[:space:]]*([0-9]+).*$ ]] && {
+      [[ $info =~ $r3 ]] && {
+        # current volume
         vol="${BASH_REMATCH[1]}"
+        [[ -a "$volfile" ]] && saved_vol="$(<"$volfile")" || saved_vol=0
+        continue
       }
-      [[ $info =~ ^application\.name[[:space:]]*=[[:space:]]*\"(.+)\"$ ]] && {
-        app="${BASH_REMATCH[1]}"
-        break
-      }
+      [[ $info =~ $r2 ]] && {
+        # are there any active clients?
+        if [[ ${BASH_REMATCH[1]} -gt 0 ]]; then
+          # dim default sink and save current volume.
+          if ((vol>saved_vol)); then
+            pacmd set-sink-volume $((index)) $((vol/2))
+            echo "$vol" > "$volfile"
+            echo "dimmed."
+            return 0
+          fi
+      elif ((vol<saved_vol)); then
+        # restore saved volume
+        pacmd set-sink-volume $((index)) $((saved_vol))
+        :> "$volfile"
+        echo "restored."
+        return 0
+      else
+        echo "nothing to do."
+        return 0
+      fi
     }
-  done < <(pacmd list-sink-inputs)
-}
-
-read_saved_volume() {
-  local application="$1"
-  [[ -a "$volfile" ]] || { echo "-"; return 1; }
-  while read -r info; do
-    [[ $info =~ ^$application\;(.+)$ ]] && {
-      echo "${BASH_REMATCH[1]}"
-      return 0
-    }
-  done < "$volfile"
-  echo "-"
-  return 1
-}
-
-remove_saved_volume() {
-  local info application="$1"
-  [[ -a "$volfile" ]] && {
-    sed -i "/^$application/d" "$volfile" &> /dev/null && return 0
   }
+  done < <(pacmd list-sinks)
   return 1
 }
 
-list_dimmed_clients() {
-  [[ -s "$volfile" ]] || { echo "[dim] no dimmed client."; return 0; }
-  while read -r info; do
-    [[ $info =~ ^(.+)\;.*$ ]] &&
-      echo "${BASH_REMATCH[1]}"
-  done < "$volfile"
+[[ $1 == "h" || $1 == "help" ]] && {
+  __help;
+  exit 0
 }
 
-for opt in "$@"; do
-  case $opt in
-    l | list    ) list_dimmed_clients; exit ;;
-    d | dim     ) DIM=1; break ;;
-    r | restore ) RESTORE=1; break ;;
-    h | help    ) __help; exit ;;
-    *           ) echo "Invalid option '$opt'!"; exit
-  esac
-done
-
-get_inputs
-[[ ${inputs[*]} ]] || { echo "[dim] not playing."; exit; }
-for input in "${inputs[@]}"; do
-
-  get_input_volume "$input"
-  saved_vol="$(read_saved_volume "$app")"
-
-  # do not dim already dimmed client
-  [[ $saved_vol == "-" ]] || { [[ $DIM ]] && continue; }
-
-  # do not restore if client is not dimmed
-  [[ $saved_vol == "-" ]] && { [[ $RESTORE ]] && continue; }
-
-  # dim only if
-  # client is not dimmed yet or
-  # if saved volume is lower or equal to actual client's volume
-  # and if RESTORE option is not set.
-  if [[ $saved_vol == "-" || $saved_vol -le $vol ]] && [[ ! $RESTORE ]]; then
-    # save application volume
-    echo "$app;$vol" >> "$volfile"
-    # dim
-    pacmd set-sink-input-volume "$input" $((vol/2)) &> /dev/null
-    echo "[${app,,}] dim on."
-    action=1
-  else
-    # restore volume if saved volume is greater or equal to actual client's volume
-    ((saved_vol>=vol)) &&
-      pacmd set-sink-input-volume $((input)) $((saved_vol)) &> /dev/null
-    # remove saved volume from file
-    remove_saved_volume "$app"
-    echo "[${app,,}] dim off."
-    action=1
-  fi
-done
-
-[[ $action ]] || echo "[dim] nothing to do."
+dim || echo "[!] there was an error."
