Fixed a bug that was making vdim useless...

diff --git a/vdim b/vdim
--- a/vdim
+++ b/vdim
@@ -1,8 +1,5 @@
 #! /usr/bin/env bash
 
-# -6dB dimmer
-# dim/restore volume of playing clients.
-
 declare volfile="$HOME/.config/speaker.volume"
 
 __help() {
@@ -16,29 +13,55 @@ Usage:
 EOB
 }
 
+get_sink_index_from_mac_address() {
+  [[ $1 ]] || return 1
+  local mac info r retry=10
+  mac=$1
+  mac="${mac//:/_}"
+  # nasty way to wait for the sink to activate...
+  while ((retry>0)); do
+    ((--retry))
+    r="^([0-9]+)[[:space:]]*.+\.$mac\..+$"
+    while read -r info; do
+      [[ $info =~ $r ]] && {
+        echo "${BASH_REMATCH[1]}"
+        return 0
+      }
+    done < <(pactl list sinks short)
+    sleep 0.125
+  done
+  return 1
+}
+
 dim() {
   local info index go r1 r2 r3 vol
+  [[ $1 ]] && {
+    index="$(get_sink_index_from_mac_address "$1")" || {
+      echo "cannot find device index"
+      return 1
+    }
+  }
   r1="^\* index:[[:space:]]*(.+)$"
-  r2="^used by:[[:space:]]*(.+)$"
-  r3="^volume:[[:space:]]*front\-left:[[:space:]]*([0-9]+).*$"
+  r2="^volume:[[:space:]]*front\-left:[[:space:]]*([0-9]+).*$"
+  r3="^used by:[[:space:]]*(.+)$"
+
   while read -r info; do
     [[ $info =~ $r1 ]] && {
-      # default sink index
-      index="${BASH_REMATCH[1]}"
+      index="${index:-"${BASH_REMATCH[1]}"}"
       go=1
       continue
     }
     [[ $go ]] && {
-      [[ $info =~ $r3 ]] && {
+      [[ $info =~ $r2 ]] && {
         # current volume
         vol="${BASH_REMATCH[1]}"
         [[ -a "$volfile" ]] && saved_vol="$(<"$volfile")" || saved_vol=0
         continue
       }
-      [[ $info =~ $r2 ]] && {
-        # are there any active clients?
+      [[ $info =~ $r3 ]] && {
+        # is there any active client?
         if [[ ${BASH_REMATCH[1]} -gt 0 ]]; then
-          # dim default sink and save current volume.
+          # dim sink and save current volume.
           if ((vol>saved_vol)); then
             pacmd set-sink-volume $((index)) $((vol/2))
             echo "$vol" > "$volfile"
@@ -66,4 +89,4 @@ dim() {
   exit 0
 }
 
-dim || echo "[!] there was an error."
+dim "$1" || echo "[!] there was an error."
